namespace KBOLauncher.Tests;

using System.Text.Json;
using System.Text.RegularExpressions;
using FluentAssertions;
using Xunit;

public sealed class KboRuntimeFlagManifestTests
{
    [Fact]
    public void RuntimeFlagManifest_MatchesGeneratedManagedDefinitions()
    {
        var manifest = ReadManifest();
        var generatedText = File.ReadAllText(RepoPath("src", "KBOLauncher", "Infrastructure", "KboFlags.RuntimeDefinitions.cs"));

        var generatedFlags = Regex.Matches(
                generatedText,
                "new\\(\"(?<key>[^\"]+)\", (?<default>null|true|false), RuntimeFlagLifecycle\\.(?<lifecycle>[A-Za-z]+)\\),")
            .Select(match => new ManifestFlagRow(
                match.Groups["key"].Value,
                match.Groups["default"].Value,
                match.Groups["lifecycle"].Value))
            .ToArray();
        var generatedSingleDivisionFlags = Regex.Matches(
                generatedText,
                "\"(?<key>enable_single_division_allstar_[^\"]+\\.txt)\",")
            .Select(match => match.Groups["key"].Value)
            .ToArray();

        generatedText.Should().Contain("<auto-generated");
        generatedFlags.Should().Equal(manifest.Flags);
        generatedSingleDivisionFlags.Should().Equal(manifest.SingleDivisionAllstarFlagKeys.Select(key => key + ".txt").ToArray());
    }

    [Fact]
    public void RuntimeFlagManifest_MatchesGeneratedNativeDefinitions()
    {
        var manifest = ReadManifest();
        var uiText = File.ReadAllText(RepoPath("native", "src", "hotkey_window", "views", "mod", "runtime_flags", "runtime_flags.generated.c"));

        var generatedUiRows = Regex.Matches(
                uiText,
                "\\{ \"(?<key>[^\"]+)\", \"(?<label>[^\"]+)\", (?<enabled>[01]), (?<default>[01]), (?<companion>NULL|\"[^\"]+\"), (?<category>KBO_MOD_FLAG_[A-Z]+) \\},")
            .Select(match => new NativeUiRow(
                match.Groups["key"].Value,
                match.Groups["label"].Value,
                int.Parse(match.Groups["enabled"].Value),
                match.Groups["default"].Value == "1",
                UnquoteNativeNull(match.Groups["companion"].Value),
                match.Groups["category"].Value))
            .ToArray();

        uiText.Should().Contain("<auto-generated");
        generatedUiRows.Should().Equal(manifest.NativeUiRows);
    }

    [Fact]
    public void RuntimeFlagManifest_CoversNativeRuntimeFlagReads()
    {
        var manifestKeys = ReadManifest().Flags
            .Select(flag => flag.Key)
            .ToHashSet(StringComparer.Ordinal);
        var nativeRoot = Path.GetDirectoryName(RepoPath("native", "KBOFix.c"))!;
        var nativeSourceFiles = Directory.EnumerateFiles(Path.Combine(nativeRoot, "src"), "*.*", SearchOption.AllDirectories)
            .Where(path => path.EndsWith(".c", StringComparison.OrdinalIgnoreCase)
                || path.EndsWith(".h", StringComparison.OrdinalIgnoreCase))
            .Concat(new[] { RepoPath("native", "KBOFix.c") });

        var nativeFlagReads = nativeSourceFiles
            .SelectMany(path => Regex.Matches(
                    File.ReadAllText(path),
                    "read_kbo_localappdata_flag_file\\(\"(?<key>[^\"]+)\"\\)")
                .Select(match => NormalizeFlagKey(match.Groups["key"].Value)))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();

        var missingFlags = nativeFlagReads
            .Where(key => !manifestKeys.Contains(key))
            .ToArray();

        missingFlags.Should().BeEmpty("every native runtime flag read should be declared in config/kbo-runtime-flags.json");
    }

    [Fact]
    public void ProductionSources_DoNotExposeRemovedForeignAiOfferGate()
    {
        var repoRoot = RepoRoot();
        var scannedFiles = new[]
            {
                Path.Combine(repoRoot, "config"),
                Path.Combine(repoRoot, "src"),
                Path.Combine(repoRoot, "native", "src"),
            }
            .SelectMany(root => Directory.EnumerateFiles(root, "*.*", SearchOption.AllDirectories))
            .Where(path => path.EndsWith(".c", StringComparison.OrdinalIgnoreCase)
                || path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
                || path.EndsWith(".h", StringComparison.OrdinalIgnoreCase)
                || path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
            .Concat(new[] { Path.Combine(repoRoot, "native", "KBOFix.c") })
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        var removedGatePattern = new Regex("fast" + "[-_ ]?" + "fill", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
        var offenders = scannedFiles
            .Where(path => removedGatePattern.IsMatch(File.ReadAllText(path)))
            .Select(path => Path.GetRelativePath(repoRoot, path))
            .Order(StringComparer.Ordinal)
            .ToArray();

        offenders.Should().BeEmpty("the removed foreign AI offer gate must not be reintroduced in production config or source");
    }

    private static RuntimeFlagManifest ReadManifest()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(RepoPath("config", "kbo-runtime-flags.json")));
        var root = doc.RootElement;
        var flags = root.GetProperty("flags")
            .EnumerateArray()
            .Select(flag => new ManifestFlagRow(
                flag.GetProperty("key").GetString()!,
                JsonBoolOrNull(flag.GetProperty("defaultValue")),
                flag.GetProperty("lifecycle").GetString()!))
            .ToArray();
        var singleDivisionAllstarFlagKeys = root.GetProperty("singleDivisionAllstarFlagKeys")
            .EnumerateArray()
            .Select(flag => flag.GetString()!)
            .ToArray();
        var uiRows = root.GetProperty("flags")
            .EnumerateArray()
            .Where(flag => flag.TryGetProperty("ui", out _))
            .Select(flag =>
            {
                var ui = flag.GetProperty("ui");
                return new NativeUiRow(
                    flag.GetProperty("key").GetString()!,
                    ui.GetProperty("label").GetString()!,
                    ui.TryGetProperty("enabledValue", out var enabledValue) ? enabledValue.GetInt32() : 1,
                    ui.GetProperty("defaultEnabled").GetBoolean(),
                    ui.TryGetProperty("companionEnableKey", out var companionEnableKey) ? companionEnableKey.GetString() : null,
                    NativeCategoryForLifecycle(flag.GetProperty("lifecycle").GetString()!));
            })
            .ToArray();

        return new RuntimeFlagManifest(flags, singleDivisionAllstarFlagKeys, uiRows);
    }

    private static string JsonBoolOrNull(JsonElement value)
    {
        return value.ValueKind switch
        {
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            JsonValueKind.Null => "null",
            _ => throw new InvalidDataException($"Expected boolean or null, got {value.ValueKind}."),
        };
    }

    private static string NativeCategoryForLifecycle(string lifecycle)
    {
        return "KBO_MOD_FLAG_" + lifecycle.ToUpperInvariant();
    }

    private static string? UnquoteNativeNull(string value)
    {
        return value == "NULL" ? null : value[1..^1];
    }

    private static string NormalizeFlagKey(string fileName)
    {
        return fileName.EndsWith(".txt", StringComparison.OrdinalIgnoreCase)
            ? fileName[..^4]
            : fileName;
    }

    private static string RepoPath(params string[] parts)
    {
        var candidate = Path.Combine(new[] { RepoRoot() }.Concat(parts).ToArray());
        if (File.Exists(candidate))
        {
            return candidate;
        }

        throw new FileNotFoundException("Could not find repository file.", Path.Combine(parts));
    }

    private static string RepoRoot()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir, "CONSTITUTION.md")))
            {
                return dir;
            }
            dir = Directory.GetParent(dir)?.FullName;
        }

        throw new FileNotFoundException("Could not find repository root.", "CONSTITUTION.md");
    }

    private sealed record RuntimeFlagManifest(
        ManifestFlagRow[] Flags,
        string[] SingleDivisionAllstarFlagKeys,
        NativeUiRow[] NativeUiRows);

    private sealed record ManifestFlagRow(string Key, string DefaultValue, string Lifecycle);

    private sealed record NativeUiRow(
        string Key,
        string Label,
        int EnabledValue,
        bool DefaultEnabled,
        string? CompanionEnableKey,
        string Category);
}
