/* <auto-generated />
   Source: config/ootp-build-abi.json */

#ifndef KBOFIX_BUILD_VERIFY_BUILD_ABI_GENERATED_H_
#define KBOFIX_BUILD_VERIFY_BUILD_ABI_GENERATED_H_

#include "build_verify.h"

#define KBO_BUILD_ABI_VALUE_COUNT 45

extern const OotpBuildAbiValue KBO_BUILD_ABI_VALUES[KBO_BUILD_ABI_VALUE_COUNT];

#endif
