/* <auto-generated />
   Source: config/ootp-build-rvas.json */

#ifndef KBOFIX_BUILD_VERIFY_BUILD_RVAS_GENERATED_H_
#define KBOFIX_BUILD_VERIFY_BUILD_RVAS_GENERATED_H_

#include "build_verify.h"

#define KBO_BUILD_RVA_COUNT 178

extern const OotpBuildRva KBO_BUILD_RVAS[KBO_BUILD_RVA_COUNT];

#endif
