/* <auto-generated />
   Source: config/ootp-supported-builds.json */

#include "supported_builds.generated.h"

const OotpSupportedBuild KBO_SUPPORTED_OOTP_BUILDS[KBO_SUPPORTED_OOTP_BUILD_COUNT] = {
    {0x69F75E6Bu, 0x03919000u, "2026-05-04 Steam", 1},
    {0x6A285052u, 0x03920000u, "2026-06-09 Steam", 0},
};
