#ifndef KBOFIX_SRC_CORE_DATES_CONSTANTS_KBO_DATE_CONSTANTS_H_
#define KBOFIX_SRC_CORE_DATES_CONSTANTS_KBO_DATE_CONSTANTS_H_

#define KBO_HISTORY_YEAR_MIN 1800u
#define KBO_TEXT_DATE_YEAR_MIN 1980u
#define KBO_SEASON_YEAR_MIN 1982u
#define KBO_SIM_YEAR_MAX 2200u
#define KBO_RUNTIME_HISTORICAL_YEAR_MAX 2100u
#define KBO_RECORD_YEAR_MAX 2300u
#define KBO_POLICY_YEAR_MAX 2400u
#define KBO_LOGO_YEAR_MAX 3000u
#define KBO_SEASON_DATE_KEY_MIN (KBO_SEASON_YEAR_MIN * 10000u)
#define KBO_SEASON_DATE_MIN (KBO_SEASON_YEAR_MIN * 10000u + 101u)
#define KBO_SIM_DATE_MAX (KBO_SIM_YEAR_MAX * 10000u + 1231u)

#define KBO_CAPTAIN_PRESEASON_START_MONTH_DAY 301u
#define KBO_CAPTAIN_PRESEASON_END_MONTH_DAY 415u

#define KBO_MILITARY_HISTORY_FALLBACK_YEAR 2001u

#endif
