#ifndef KBOFIX_BOOTSTRAP_OOTP_OFFSETS_H
#define KBOFIX_BOOTSTRAP_OOTP_OFFSETS_H

/* ---- Capacity constants ---- */
#define OOTP27_KBO_MAX_SPECIAL_HISTORY_KEYS  8192
#define OOTP27_KBO_MAX_ALLSTAR_TEAM_ROWS     8192

/* ---- Build-specific RVAs ---- */
#include "ootp_rvas.generated.h"

/* ---- Native league events/news ---- */
#define OOTP27_PLAYER_TOOLTIP_HOVER_MANAGER_STOLEN_LEN 17u
#define OOTP27_PLAYER_TOOLTIP_TEXT_APPEND_STOLEN_LEN 18u
#define OOTP27_PLAYER_TOOLTIP_STRING_FORMAT_STOLEN_LEN 24u
#define OOTP27_PLAYER_TOOLTIP_RATING_COMMON_STOLEN_LEN 15u
#define OOTP27_PLAYER_TOOLTIP_RATING_PANEL_CTOR_STOLEN_LEN 15u
#define OOTP27_DRAFT_ORDER_CREATE_STOLEN_LEN 12u
#define OOTP27_AMATEUR_ASSIGNMENT_BATCH_PREP_STOLEN_LEN 17u
#define OOTP27_FA_SIGNING_BRANCH_PATCH_OFFSET 0x27u
#define OOTP27_FA_SIGNING_BRANCH_POST_SUCCESS_OFFSET 0x74u
#define OOTP27_INTL_ESTABLISHED_FA_REGISTER_GATE_STOLEN_LEN 15u
#define OOTP27_INTL_ESTABLISHED_FA_REGISTER_CALL_OFFSET 10u
#define OOTP27_ALLSTAR_CANDIDATE_TEAM_SPLIT_VECTOR_CALL_OFFSET 0xA5u
#define OOTP27_ALLSTAR_CANDIDATE_TEAM_ROSTER_PUSH_CALL_OFFSET 3u
#define OOTP27_ALLSTAR_CANDIDATE_TEAM_ROSTER_PUSH_STOLEN_LEN 16u
#define OOTP27_ALLSTAR_CANDIDATE_PLAYER_PUSH_CALL_OFFSET 0x03u
#define OOTP27_ALLSTAR_CANDIDATE_PLAYER_PUSH_STOLEN_LEN 15u
#define OOTP27_ALLSTAR_CANDIDATE_PLAYER_PUSH_SKIP_DELTA 0x85u
#define OOTP27_ALLSTAR_CANDIDATE_RANKED_PLAYER_PUSH_STOLEN_LEN 26u
#define OOTP27_ALLSTAR_CANDIDATE_RANKED_PLAYER_PUSH_CALL_OFFSET 14u
#define OOTP27_ALLSTAR_TEAM_SETUP_BAIL_CONTEXT_FROM_FUNC_DELTA 0x000000C2u
#define OOTP27_MAKE_ALLSTAR_EVENTS_PREP_CALL_OFFSET 14u
#define OOTP27_MESSAGE_OBJECT_SIZE 0xA8u
#define OOTP27_NEWS_RELATED_PLAYERS_OFFSET 0x08u
#define OOTP27_NEWS_RELATED_TEAMS_OFFSET 0x30u
#define OOTP27_NEWS_LEAGUE_ID_OFFSET 0x44u
#define OOTP27_NEWS_CATEGORY_OFFSET 0x50u
#define OOTP27_NEWS_FLAGS_54_OFFSET 0x54u
#define OOTP27_NEWS_FLAGS_58_OFFSET 0x58u
#define OOTP27_NEWS_TYPE_OFFSET 0x5Cu
#define OOTP27_NEWS_SECONDARY_LEAGUE_ID_OFFSET 0x60u
#define OOTP27_NEWS_TEAM_ID_OFFSET 0x64u
#define OOTP27_NEWS_PLAYER_ID_OFFSET 0x68u
#define OOTP27_NEWS_YEAR_OFFSET 0x78u
#define OOTP27_NEWS_DAY_OFFSET 0x7Au
#define OOTP27_NEWS_MONTH_OFFSET 0x7Bu
#define OOTP27_NEWS_STATUS_OFFSET 0x7Cu
#define OOTP27_NEWS_PRIORITY_OFFSET 0x80u
#define OOTP27_NEWS_RELATED_ID_OFFSET 0x84u
#define OOTP27_NEWS_VISIBLE_OFFSET 0x88u
#define OOTP27_MESSAGE_OBJECT_ID_OFFSET 0x8Cu
#define OOTP27_MESSAGE_SAVE_PATH_OFFSET 0x1A58u

/* ---- Live/news date object offsets ---- */
#define OOTP27_LIVE_DATE_OBJECT_OFFSET 0x1B0u
#define OOTP27_LIVE_DATE_OBJECT_READABLE_BYTES 16u

/* ---- Foreign FA offer UI object offsets ---- */
#define OOTP27_FA_OFFER_SCREEN_PLAYER_ID_OFFSET 0xB8u
#define OOTP27_FA_OFFER_SCREEN_OWNER_OFFSET 0xC8u
#define OOTP27_FA_OFFER_SCREEN_SUBMIT_CONTROL_OFFSET 0x2E0u
#define OOTP27_FA_OFFER_SCREEN_MAJOR_OPTION_CONTROL_OFFSET 0x2F0u
#define OOTP27_FA_OFFER_SCREEN_CONTRACT_TYPE_CONTROL_OFFSET 0x2F8u
#define OOTP27_FA_OFFER_SCREEN_OWNER_MODE_OFFSET 0x104u

/* ---- Foreign FA contract offer object offsets ---- */
#define OOTP27_FA_CONTRACT_OFFER_PLAYER_ID_OFFSET 0xBCu
#define OOTP27_FA_CONTRACT_OFFER_SALARY_OFFSET 0xC0u
#define OOTP27_FA_CONTRACT_OFFER_OPTION_SALARY_OFFSET 0xC8u
#define OOTP27_FA_CONTRACT_OFFER_MAJOR_FLAG_OFFSET 0xCCu

/* ---- Financials object offsets ---- */
#define OOTP27_FINANCIALS_AVERAGE_SALARY_OFFSET 0x29Cu
#define OOTP27_FINANCIALS_PROBE_FIRST_OFFSET 0x278u
#define OOTP27_FINANCIALS_PROBE_SECONDARY_FIRST_OFFSET 0x360u
#define OOTP27_FINANCIALS_PROBE_LAST_OFFSET 0x390u
#define OOTP27_FINANCIALS_SALARY_LADDER_MINIMUM_OFFSET 0x278u
#define OOTP27_FINANCIALS_SALARY_LADDER_POOR_OFFSET 0x280u
#define OOTP27_FINANCIALS_SALARY_LADDER_FAIR_OFFSET 0x284u
#define OOTP27_FINANCIALS_SALARY_LADDER_BELOW_AVERAGE_OFFSET 0x288u
#define OOTP27_FINANCIALS_SALARY_LADDER_AVERAGE_OFFSET 0x28cu
#define OOTP27_FINANCIALS_SALARY_LADDER_ABOVE_AVERAGE_OFFSET 0x290u
#define OOTP27_FINANCIALS_SALARY_LADDER_GOOD_OFFSET 0x294u
#define OOTP27_FINANCIALS_SALARY_LADDER_STAR_OFFSET 0x298u
#define OOTP27_FINANCIALS_SALARY_LADDER_SUPERSTAR_OFFSET 0x29cu
#define OOTP27_FINANCIALS_FA_DEMAND_CEILING_OFFSET 0x374u

/* ---- Salary arbitration player/patch offsets ---- */
#define OOTP27_PLAYER_ARBITRATION_OFFER_OFFSET 0x87cu
#define OOTP27_PLAYER_ARBITRATION_REQUEST_OFFSET 0x880u
#define OOTP27_PLAYER_CONTRACT_TOTAL_YEARS_OFFSET 0x914u
#define OOTP27_PLAYER_CONTRACT_CURRENT_YEAR_OFFSET 0x915u
#define OOTP27_PLAYER_ARBITRATION_STATUS_OFFSET 0xdb0u
#define OOTP27_PLAYER_ARBITRATION_TENDER_FLAG_OFFSET 0xdbfu

/* ---- Patch-only branch target RVAs ---- */

/* ---- Historical/season phase probe offsets ---- */
#define OOTP27_HISTORICAL_LEAGUE_READABLE_BYTES 0x4cc8u
#define OOTP27_HISTORICAL_LEAGUE_GATE_OFFSET 0x2e5u
#define OOTP27_SEASON_PHASE_CANDIDATE_READABLE_BYTES 0x4cd0u
#define OOTP27_SEASON_PHASE_ALT_ID_A_OFFSET 0x4cc4u
#define OOTP27_SEASON_PHASE_ALT_ID_B_OFFSET 0x4cc8u
#define OOTP27_SEASON_PHASE_ALT_ID_C_OFFSET 0x4cccu
#define OOTP27_SEASON_PHASE_PROBE_BASE_OFFSET 0x44d0u
#define OOTP27_SEASON_PHASE_PROBE_BYTES 0x70u

/* ---- AI FA status candidate frame offsets ---- */
#define OOTP27_AI_FA_STATUS_FRAME_TEAM_PTR_OFFSET 0x140u
#define OOTP27_AI_FA_STATUS_FRAME_INSERT_COUNT_DELTA 0x2cu
#define OOTP27_AI_FA_OFFER_FRAME_TEAM_PTR_OFFSET 0x540u

/* ---- All-star league layout child object offsets ---- */
#define OOTP27_ALLSTAR_LEAGUE_CONTEXT_VTABLE_METHOD_OFFSET 0x30u
#define OOTP27_SUBLEAGUE_DIVISION_ARRAY_OFFSET 0x40u
#define OOTP27_SUBLEAGUE_DIVISION_COUNT_OFFSET 0x4cu
#define OOTP27_SUBLEAGUE_READABLE_BYTES 0x50u
#define OOTP27_DIVISION_TEAM_IDS_BEGIN_OFFSET 0x20u
#define OOTP27_DIVISION_TEAM_IDS_END_OFFSET 0x28u
#define OOTP27_DIVISION_READABLE_BYTES 0x30u

/* ---- Generic global vector layout offsets ---- */
#define OOTP27_GLOBAL_VECTOR_COUNT_DELTA 0x0cu

#include "detail/ootp_offsets_player.h"

/* ---- Team offsets ---- */
#define OOTP27_KBO_TEAM_VECTOR_OFFSET     0x90u
#define OOTP27_KBO_TEAM_COUNT_OFFSET      0x9cu
#define OOTP27_KBO_TEAM_LEAGUE_ID_OFFSET  0x120u
#define OOTP27_KBO_TEAM_NATION_ID_OFFSET  0x128u
#define OOTP27_KBO_TEAM_PARENT_TEAM_ID_OFFSET 0x130u
#define OOTP27_KBO_TEAM_DELETED_OFFSET    0xc58u
#define OOTP27_KBO_TEAM_ACTIVE_OFFSET     0xc59u
#define OOTP27_KBO_TEAM_ID_OFFSET         0x4450u
#define OOTP27_KBO_TEAM_READABLE_BYTES    0x4460u
#define OOTP27_KBO_TEAM_PRIMARY_COLOR_OFFSET   0xc4cu
#define OOTP27_KBO_TEAM_UI_TINT_COLOR_OFFSET   0xc50u
#define OOTP27_KBO_TEAM_SECONDARY_COLOR_OFFSET 0xc54u
#define OOTP27_KBO_TEAM_REGULAR_WINS_OFFSET   0x400cu
#define OOTP27_KBO_TEAM_REGULAR_LOSSES_OFFSET 0x4018u
#define OOTP27_KBO_TEAM_REGULAR_TIES_OFFSET   0x401cu
#define OOTP27_KBO_STRING_OBJECT_TEXT_OFFSET 0x8u
#define OOTP27_KBO_TEAM_CITY_STRING_OFFSET   0x10u
#define OOTP27_KBO_TEAM_NICKNAME_STRING_OFFSET 0x28u
#define OOTP27_KBO_TEAM_FULL_NAME_STRING_OFFSET 0x40u
#define OOTP27_KBO_TEAM_ABBR_STRING_OFFSET 0x58u
#define OOTP27_KBO_TEAM_SHORT_NAME_STRING_OFFSET 0x70u
#define OOTP27_KBO_TEAM_ALT_NAME_STRING_OFFSET 0x100u
#define OOTP27_KBO_TEAM_SEARCH_STRING_OFFSETS \
    { \
        OOTP27_KBO_TEAM_CITY_STRING_OFFSET, \
        OOTP27_KBO_TEAM_NICKNAME_STRING_OFFSET, \
        OOTP27_KBO_TEAM_FULL_NAME_STRING_OFFSET, \
        OOTP27_KBO_TEAM_ABBR_STRING_OFFSET, \
        OOTP27_KBO_TEAM_SHORT_NAME_STRING_OFFSET, \
        OOTP27_KBO_TEAM_ALT_NAME_STRING_OFFSET \
    }

#define OOTP27_PLAYER_EXPORT_KEY_STRING_OFFSET_A 0x1138u
#define OOTP27_PLAYER_EXPORT_KEY_STRING_OFFSET_B 0x1180u
#define OOTP27_PLAYER_EXPORT_KEY_STRING_OFFSET_C 0x1198u
#define OOTP27_PLAYER_CHADWICK_ID_STRING_OFFSET 0x1210u
#define OOTP27_PLAYER_MLB_ID_STRING_OFFSET 0x1228u
#define OOTP27_PLAYER_EXPORT_KEY_STRING_OFFSETS \
    { \
        OOTP27_PLAYER_EXPORT_KEY_STRING_OFFSET_A, \
        OOTP27_PLAYER_EXPORT_KEY_STRING_OFFSET_B, \
        OOTP27_PLAYER_EXPORT_KEY_STRING_OFFSET_C \
    }

/* ---- Team roster array offsets ---- */
#define OOTP27_TEAM_PLAYER_IDS_2760_OFFSET         0x2760u
#define OOTP27_TEAM_PLAYER_IDS_2A80_OFFSET         0x2a80u
#define OOTP27_TEAM_PLAYER_IDS_2DA0_OFFSET         0x2da0u
#define OOTP27_TEAM_RESTRICTED_PLAYER_IDS_OFFSET   0x30c0u
#define OOTP27_TEAM_PLAYER_IDS_33E0_OFFSET         0x33e0u
#define OOTP27_TEAM_PLAYER_IDS_3700_OFFSET         0x3700u
#define OOTP27_TEAM_PLAYER_ID_ARRAY_COUNT          200u

/* ---- Global DB offsets ---- */
#define OOTP27_GLOBAL_HUMAN_MANAGER_VECTOR_OFFSET 0xf0u
#define OOTP27_GLOBAL_HUMAN_MANAGER_COUNT_OFFSET  0xfcu
#define OOTP27_GLOBAL_CURRENT_DATE_OFFSET          0x2d8u
#define OOTP27_GLOBAL_CURRENT_LEAGUE_OFFSET        0x2e0u
#define OOTP27_GLOBAL_SQL_DATABASE_OFFSET          0x2d78u
#define OOTP27_GLOBAL_SQL_ENABLED_OFFSET           0x2df0u
#define OOTP27_GLOBAL_CURRENT_LEAGUE_ID_OFFSET     0x48u
#define OOTP27_LEAGUE_MINIMUM_SALARY_OFFSET        0x278u
#define OOTP27_CURRENT_DATE_YEAR_OFFSET            0x1b8u
#define OOTP27_CURRENT_DATE_MONTH_OFFSET           0x1bbu
#define OOTP27_CURRENT_DATE_DAY_OFFSET             0x1bau

/* ---- Amateur draft order offsets ---- */
#define OOTP27_LEAGUE_PRIMARY_DRAFT_STATE_OFFSET 0x768u
#define OOTP27_DRAFT_STATE_ORDER_VECTOR_OFFSET     0x88u
#define OOTP27_DRAFT_STATE_ORDER_COUNT_OFFSET      0x94u
#define OOTP27_DRAFT_STATE_READABLE_BYTES          0x98u
#define OOTP27_DRAFT_ORDER_ROW_ORIGINAL_TEAM_OFFSET 0x00u
#define OOTP27_DRAFT_ORDER_ROW_OWNER_TEAM_OFFSET    0x04u
#define OOTP27_DRAFT_ORDER_ROW_ROUND_OFFSET         0x08u
#define OOTP27_DRAFT_ORDER_ROW_PICK_OFFSET          0x0au
#define OOTP27_DRAFT_ORDER_ROW_PLAYER_ID_OFFSET     0x0cu
#define OOTP27_DRAFT_ORDER_ROW_SUPPLEMENTAL_OFFSET  0x0eu
#define OOTP27_DRAFT_ORDER_ROW_READABLE_BYTES       0x10u

/* ---- Human manager offsets ---- */
#define OOTP27_HUMAN_CONTROL_CONTEXT_READABLE_BYTES         0x68u
#define OOTP27_HUMAN_CONTROL_CONTEXT_LEAGUE_ID_OFFSET       0x48u
#define OOTP27_HUMAN_CONTROL_CONTEXT_TEAM_ID_OFFSET         0x58u
#define OOTP27_HUMAN_CONTROL_CONTEXT_TEAM_ID_CONFIRM_OFFSET 0x60u

/* ---- League custom events ---- */
#define OOTP27_EVENT_MANAGER_EVENT_VECTOR_OFFSET   0x250u
#define OOTP27_EVENT_MANAGER_EVENT_COUNT_OFFSET    0x25cu
#define OOTP27_LEAGUE_EVENT_LEAGUE_ID_OFFSET       0x08u
#define OOTP27_LEAGUE_EVENT_YEAR_OFFSET            0x18u
#define OOTP27_LEAGUE_EVENT_DAY_OFFSET             0x1au
#define OOTP27_LEAGUE_EVENT_MONTH_OFFSET           0x1bu
#define OOTP27_LEAGUE_EVENT_TYPE_OFFSET            0x20u
#define OOTP27_LEAGUE_EVENT_EVENT_OVER_OFFSET      0x22u
#define OOTP27_LEAGUE_EVENT_DELETED_OFFSET         0x23u
#define OOTP27_LEAGUE_EVENT_NAME_STRING_OFFSET     0x28u
#define OOTP27_EVENT_TYPE_CUSTOM_EVENT             0u
#define OOTP27_EVENT_TYPE_DRAFT_POOL_ANNOUNCEMENT  3u

/* ---- League offsets ---- */
#define OOTP27_KBO_LEAGUE_ID_OFFSET    0x4cc0u
#define OOTP27_KBO_LEAGUE_FINANCIALS_REDIRECT_LEAGUE_ID_OFFSET 0x44e8u
#define OOTP27_KBO_LEAGUE_YEAR_OFFSET  0x44ecu
#define OOTP27_KBO_LEAGUE_PHASE_OFFSET 0x44f0u
#define OOTP27_KBO_LEAGUE_PHASE_YEAR_OFFSET 0x44f4u
#define OOTP27_KBO_LEAGUE_NAME_STRING_OFFSET 0x38u
#define OOTP27_KBO_LEAGUE_ABBR_STRING_OFFSET 0x50u
#define OOTP27_KBO_LEAGUE_LOGO_STRING_OFFSET 0x68u
#define OOTP27_KBO_LEAGUE_SUBLEAGUE_COUNT_OFFSET 0x4a3cu
#define OOTP27_KBO_LEAGUE_STATS_PATH_STRING_OFFSET 0x4530u
#define OOTP27_KBO_LEAGUE_SCHEDULE_FILE_STRING_OFFSET 0x4a00u

#include "ootp_offsets_dates.h"

#endif
