#ifndef KBOFIX_SRC_CORE_DATES_TICK_CURRENT_DATE_TICK_WATCHPOINT_H_
#define KBOFIX_SRC_CORE_DATES_TICK_CURRENT_DATE_TICK_WATCHPOINT_H_

void start_kbo_current_date_tick_watchpoint_thread(void);

#endif
