#ifndef KBOFIX_SRC_CORE_PRODUCT_OOTP_PRODUCT_H_
#define KBOFIX_SRC_CORE_PRODUCT_OOTP_PRODUCT_H_

#define KBO_PRODUCT_LOCAL_DATA_DIR "OOTP-KBO"
#define KBO_PRODUCT_LOCAL_DATA_DIR_W L"OOTP-KBO"
#define KBO_PRODUCT_DATA_BUNDLE_FILE "kbo_data_bundle.json"
#define KBO_PRODUCT_SAVE_SCOPED_DATA_DIR "saves"
#define KBO_PRODUCT_PERF_DIR "perf"

#define KBO_OOTP_EXECUTABLE_NAME "ootp27.exe"
#define KBO_OOTP_EXECUTABLE_NAME_UPPER "OOTP27.EXE"
#define KBO_OOTP_PRODUCT_SHORT_NAME "OOTP 27"
#define KBO_OOTP_VENDOR_FOLDER "Out of the Park Developments"
#define KBO_OOTP_PRODUCT_FOLDER "OOTP Baseball 27"
#define KBO_OOTP_PRODUCT_LONG_FOLDER "Out of the Park Baseball 27"
#define KBO_OOTP_DATA_DIR "data"
#define KBO_OOTP_SCHEDULES_DIR "schedules"
#define KBO_OOTP_KBO_SCHEDULE_PREFIX "korean_baseball_organization_int_c_"
#define KBO_OOTP_KBO_SCHEDULE_EXTENSION ".lsdl"
#define KBO_OOTP_SAVE_EXTENSION ".lg"
#define KBO_OOTP_SAVE_DESCRIPTION_FILE "description.txt"
#define KBO_OOTP_SAVE_STARTED_FILE "flag_save_started.dat"
#define KBO_OOTP_SAVE_COMPLETED_FILE "flag_save_completed.dat"
#define KBO_OOTP_SAVE_COMPLETED_SENTINEL "Finished save_database, closing flag file now"
#define KBO_OOTP_TEXT_DATA_TEMP_DIR "temp"
#define KBO_OOTP_TEXT_DATA_SQLITE_FILE "text_data.sqlite3"
#define KBO_PRODUCT_FLAGS_JSON_FILE "kbo_flags.json"
#define KBO_PRODUCT_SETTINGS_JSON_FILE "kbo_settings.json"
#define KBO_PRODUCT_SAVE_STATE_SQLITE_FILE "kbo_state.sqlite3"
#define KBO_PRODUCT_LEAGUE_ID_FILE "kbo_league_id.txt"
#define KBO_PRODUCT_CURRENT_SAVE_PATH_FILE_FORMAT "current_save_path_%lu.txt"
#define KBO_PRODUCT_ROSTER_MARKER_STATUS_FILE "launcher_roster_marker_guard_status.txt"
#define KBO_PRODUCT_REPOSITORY_NAME "OOTP27_Ultimate_KBO"
#define KBO_PRODUCT_REPOSITORY_OWNER "lebronisbest623"
#define KBO_PRODUCT_REPOSITORY_HOST_LABEL "github.com/lebronisbest623"
#define KBO_PRODUCT_REQUIRED_ROSTER_MARKER_URL "https://github.com/lebronisbest623/OOTP27_Ultimate_KBO"
#define KBO_PRODUCT_PERF_FILE_FORMAT "kbo_perf_%lu.csv"
#define KBO_PRODUCT_PERF_FILE_PATTERN "kbo_perf_*.csv"

#endif
