"""Constants shared by KBO optimizer modes.

Values are part of the optimizer behavior contract. Change them only with
golden fixture updates that explain the intended gameplay effect.
"""

# 학교 리그 식별자와 팀별 정원 상한. 값은 OOTP/KBO 시드 계약에 묶여 있다.
KBO_COLLEGE_LEAGUE_ID = 201
KBO_HIGH_SCHOOL_LEAGUE_ID = 203
KBO_COLLEGE_TEAM_MAX_PLAYERS = 40
KBO_HIGH_SCHOOL_TEAM_MAX_PLAYERS = 34
KBO_COLLEGE_TEAM_MIN_PLAYERS = 24
KBO_HIGH_SCHOOL_TEAM_MIN_PLAYERS = 24
AMATEUR_MIN_HITTERS_PER_TEAM = 11
AMATEUR_MIN_PITCHERS_PER_TEAM = 8

# 아마추어 배정 점수. 값 변경은 draft/roster 골든 출력으로 먼저 검증한다.
MIN_TEAM_FILL_BONUS = 80000
RANK_FIT_WEIGHT = 12000
RANK_MISMATCH_PENALTY = 4200
ASSORTATIVE_RANK_WEIGHT = 100000
TOP_EDGE_BONUS = 2800
BOTTOM_EDGE_BONUS = 2200
EXTREME_MISMATCH_PENALTY = 3600
OPTIONAL_SLOT_REPUTATION_WEIGHT = 30000
INCOMING_REPUTATION_FLOOR_WEIGHT = 0.03
INCOMING_REPUTATION_POWER = 3.0
INCOMING_SLOT_DECAY = 1.15
INCOMING_MAX_AVERAGE_MULTIPLIER = 2.65
AMATEUR_ROLE_BALANCE_TOLERANCES = (0.10, 0.15, 0.22, 0.50)
AMATEUR_MIN_HITTER_SHARE = 0.25
AMATEUR_MAX_HITTER_SHARE = 0.75
AMATEUR_POSITION_BUCKETS = ("P", "C", "1B", "2B", "3B", "SS", "LF", "CF", "RF")

# 아시안게임 로스터 형태와 소프트 제약 가중치.
ASIAN_GAMES_ROSTER_SIZE = 24
ASIAN_GAMES_ROLE_TARGETS = {
    "P": 11,
    "C": 2,
    "IF": 6,
    "OF": 5,
}
ASIAN_GAMES_ROLE_MINIMUMS = {
    "P": 9,
    "C": 2,
    "IF": 5,
    "OF": 4,
}
ASIAN_GAMES_ROLE_MAXIMUMS = {
    "P": 13,
    "C": 3,
    "IF": 8,
    "OF": 7,
}
ASIAN_GAMES_MAX_WILDCARDS = 3
ASIAN_GAMES_TEAM_MAX_PLAYERS = 3
ASIAN_GAMES_REQUIRED_ORG_BONUS = 250000
ASIAN_GAMES_ROLE_DEVIATION_PENALTY = 160000

# 병역/FA 보상 선택의 보조 tie-break 가중치.
MILITARY_SELECTION_TEAM_SPREAD_BONUS = 250
FA_PROTECTION_ROLE_BONUS = 25
